# multi_agent_system/docker/docker-compose.yml

version: '3.8'

services:
  orchestrator_server:
    build:
      context: ../
      dockerfile: docker/Dockerfile.server
    container_name: multi_agent_server
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      # Pass API keys as environment variables
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - BRAVE_SEARCH_API_KEY=${BRAVE_SEARCH_API_KEY}
    networks:
      - agent_network
    depends_on:
      - weather_agent
      - web_search_agent
      - news_agent
    # Mount config for orchestrator to read agent_config.yaml
    volumes:
      - ../config:/app/config

  weather_agent:
    build:
      context: ../
      dockerfile: docker/Dockerfile.agent
    container_name: weather_agent
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      # This A2A endpoint must match agent_config.yaml
      - A2A_ENDPOINT=http://weather_agent:5001/a2a # Use service name as host
    ports:
      - "5001:5001"
    command: python scripts/start_agents.py --agent weather_agent # Custom command to start specific agent
    networks:
      - agent_network
    volumes:
      - ../config:/app/config # Mount config to access agent_config.yaml for startup parameters

  web_search_agent:
    build:
      context: ../
      dockerfile: docker/Dockerfile.agent
    container_name: web_search_agent
    environment:
      - BRAVE_SEARCH_API_KEY=${BRAVE_SEARCH_API_KEY}
      - A2A_ENDPOINT=http://web_search_agent:5002/a2a
    ports:
      - "5002:5002"
    command: python scripts/start_agents.py --agent web_search_agent
    networks:
      - agent_network
    volumes:
      - ../config:/app/config

  news_agent:
    build:
      context: ../
      dockerfile: docker/Dockerfile.agent
    container_name: news_agent
    environment:
      - NEWS_API_KEY=${NEWS_API_KEY}
      - A2A_ENDPOINT=http://news_agent:5003/a2a
    ports:
      - "5003:5003"
    command: python scripts/start_agents.py --agent news_agent
    networks:
      - agent_network
    volumes:
      - ../config:/app/config

networks:
  agent_network:
    driver: bridge